services:
  - type: web
    name: nfl-discord-bot
    env: node
    region: oregon
    plan: starter
    buildCommand: npm install
    startCommand: node index.js
    healthCheckPath: /health
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
    autoDeploy: true